USE Atelier2
GO

SET NUMERIC_ROUNDABORT OFF;

SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL,
ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON;
GO

CREATE VIEW View_4 With SCHEMABINDING
AS
SELECT id_order_material, Cost
FROM dbo.Order_material
WHERE Cost BETWEEN 500 and 1500
GO

CREATE UNIQUE CLUSTERED INDEX Index_On_View ON View_4 (id_order_material,Cost) 

SET STATISTICS TIME ON;

SELECT * 
FROM View_4
GO

SET STATISTICS TIME OFF;

DROP VIEW View_4